package pl.greenislanddev.prawojazdy.business.sql;

import pl.greenislanddev.prawojazdy.R;
import android.database.sqlite.SQLiteDatabase;

public class Category7DataCreator extends DbDataCreator {

	public void initData(final SQLiteDatabase db) {
		insertQuestion(db,R.string.question273, R.array.answers273,R.array.correct_answers273, R.string.category8, R.drawable.b259);
		insertQuestion(db,R.string.question274, R.array.answers274,R.array.correct_answers274, R.string.category8, R.drawable.b260);
		insertQuestion(db,R.string.question275, R.array.answers275,R.array.correct_answers275, R.string.category8, R.drawable.brak);
		insertQuestion(db,R.string.question276, R.array.answers276,R.array.correct_answers276, R.string.category8, R.drawable.b263);
		insertQuestion(db,R.string.question277, R.array.answers277,R.array.correct_answers277, R.string.category8, R.drawable.b264);
		insertQuestion(db,R.string.question278, R.array.answers278,R.array.correct_answers278, R.string.category8, R.drawable.b265);
		insertQuestion(db,R.string.question279, R.array.answers279,R.array.correct_answers279, R.string.category8, R.drawable.brak);
		insertQuestion(db,R.string.question280, R.array.answers280,R.array.correct_answers280, R.string.category8, R.drawable.brak);
		insertQuestion(db,R.string.question281, R.array.answers281,R.array.correct_answers281, R.string.category8, R.drawable.brak);
		insertQuestion(db,R.string.question282, R.array.answers282,R.array.correct_answers282, R.string.category8, R.drawable.brak);
		insertQuestion(db,R.string.question283, R.array.answers283,R.array.correct_answers283, R.string.category8, R.drawable.brak);
		insertQuestion(db,R.string.question284, R.array.answers284,R.array.correct_answers284, R.string.category8, R.drawable.b271);
		insertQuestion(db,R.string.question285, R.array.answers285,R.array.correct_answers285, R.string.category8, R.drawable.b272);
		insertQuestion(db,R.string.question286, R.array.answers286,R.array.correct_answers286, R.string.category8, R.drawable.b273);
		insertQuestion(db,R.string.question287, R.array.answers287,R.array.correct_answers287, R.string.category8, R.drawable.b274);
		insertQuestion(db,R.string.question288, R.array.answers288,R.array.correct_answers288, R.string.category8, R.drawable.b275);
		insertQuestion(db,R.string.question289, R.array.answers289,R.array.correct_answers289, R.string.category8, R.drawable.b277);
		insertQuestion(db,R.string.question290, R.array.answers290,R.array.correct_answers290, R.string.category8, R.drawable.b278);
		insertQuestion(db,R.string.question291, R.array.answers291,R.array.correct_answers291, R.string.category8, R.drawable.b279);
		insertQuestion(db,R.string.question292, R.array.answers292,R.array.correct_answers292, R.string.category8, R.drawable.b280);
		insertQuestion(db,R.string.question293, R.array.answers293,R.array.correct_answers293, R.string.category8, R.drawable.b1193);
		insertQuestion(db,R.string.question294, R.array.answers294,R.array.correct_answers294, R.string.category8, R.drawable.b1194);
		insertQuestion(db,R.string.question295, R.array.answers295,R.array.correct_answers295, R.string.category8, R.drawable.brak);
		insertQuestion(db,R.string.question296, R.array.answers296,R.array.correct_answers296, R.string.category8, R.drawable.brak);
		insertQuestion(db,R.string.question297, R.array.answers297,R.array.correct_answers297, R.string.category8, R.drawable.brak);
		insertQuestion(db,R.string.question298, R.array.answers298,R.array.correct_answers298, R.string.category9, R.drawable.b281);
		insertQuestion(db,R.string.question299, R.array.answers299,R.array.correct_answers299, R.string.category9, R.drawable.b282);
		insertQuestion(db,R.string.question300, R.array.answers300,R.array.correct_answers300, R.string.category9, R.drawable.b283);
		insertQuestion(db,R.string.question301, R.array.answers301,R.array.correct_answers301, R.string.category9, R.drawable.b284);
		insertQuestion(db,R.string.question302, R.array.answers302,R.array.correct_answers302, R.string.category9, R.drawable.b285);
		insertQuestion(db,R.string.question303, R.array.answers303,R.array.correct_answers303, R.string.category9, R.drawable.b286);
		insertQuestion(db,R.string.question304, R.array.answers304,R.array.correct_answers304, R.string.category9, R.drawable.b287);
		insertQuestion(db,R.string.question305, R.array.answers305,R.array.correct_answers305, R.string.category9, R.drawable.b288);
		insertQuestion(db,R.string.question306, R.array.answers306,R.array.correct_answers306, R.string.category9, R.drawable.b289);
		insertQuestion(db,R.string.question307, R.array.answers307,R.array.correct_answers307, R.string.category9, R.drawable.b290);
		insertQuestion(db,R.string.question308, R.array.answers308,R.array.correct_answers308, R.string.category9, R.drawable.brak);
		insertQuestion(db,R.string.question309, R.array.answers309,R.array.correct_answers309, R.string.category9, R.drawable.b292);
		insertQuestion(db,R.string.question310, R.array.answers310,R.array.correct_answers310, R.string.category9, R.drawable.b293);
		insertQuestion(db,R.string.question311, R.array.answers311,R.array.correct_answers311, R.string.category9, R.drawable.b294);
		insertQuestion(db,R.string.question312, R.array.answers312,R.array.correct_answers312, R.string.category9, R.drawable.b295);
		insertQuestion(db,R.string.question313, R.array.answers313,R.array.correct_answers313, R.string.category9, R.drawable.b296);
		insertQuestion(db,R.string.question314, R.array.answers314,R.array.correct_answers314, R.string.category9, R.drawable.brak);
		insertQuestion(db,R.string.question315, R.array.answers315,R.array.correct_answers315, R.string.category9, R.drawable.brak);
		insertQuestion(db,R.string.question316, R.array.answers316,R.array.correct_answers316, R.string.category9, R.drawable.b300);
		insertQuestion(db,R.string.question317, R.array.answers317,R.array.correct_answers317, R.string.category9, R.drawable.brak);
		insertQuestion(db,R.string.question318, R.array.answers318,R.array.correct_answers318, R.string.category9, R.drawable.brak);
		insertQuestion(db,R.string.question319, R.array.answers319,R.array.correct_answers319, R.string.category10, R.drawable.brak);
		insertQuestion(db,R.string.question320, R.array.answers320,R.array.correct_answers320, R.string.category10, R.drawable.brak);
		insertQuestion(db,R.string.question321, R.array.answers321,R.array.correct_answers321, R.string.category10, R.drawable.brak);
		insertQuestion(db,R.string.question322, R.array.answers322,R.array.correct_answers322, R.string.category10, R.drawable.brak);
		insertQuestion(db,R.string.question323, R.array.answers323,R.array.correct_answers323, R.string.category10, R.drawable.b307);
		insertQuestion(db,R.string.question324, R.array.answers324,R.array.correct_answers324, R.string.category10, R.drawable.b308);
		insertQuestion(db,R.string.question325, R.array.answers325,R.array.correct_answers325, R.string.category10, R.drawable.b309);
		insertQuestion(db,R.string.question326, R.array.answers326,R.array.correct_answers326, R.string.category10, R.drawable.b310);
		insertQuestion(db,R.string.question327, R.array.answers327,R.array.correct_answers327, R.string.category10, R.drawable.b311);
		insertQuestion(db,R.string.question328, R.array.answers328,R.array.correct_answers328, R.string.category10, R.drawable.brak);
		insertQuestion(db,R.string.question329, R.array.answers329,R.array.correct_answers329, R.string.category10, R.drawable.brak);
		insertQuestion(db,R.string.question330, R.array.answers330,R.array.correct_answers330, R.string.category10, R.drawable.brak);
		insertQuestion(db,R.string.question331, R.array.answers331,R.array.correct_answers331, R.string.category10, R.drawable.brak);
		insertQuestion(db,R.string.question332, R.array.answers332,R.array.correct_answers332, R.string.category10, R.drawable.brak);
		insertQuestion(db,R.string.question333, R.array.answers333,R.array.correct_answers333, R.string.category10, R.drawable.brak);
		insertQuestion(db,R.string.question334, R.array.answers334,R.array.correct_answers334, R.string.category10, R.drawable.b319);
		insertQuestion(db,R.string.question335, R.array.answers335,R.array.correct_answers335, R.string.category10, R.drawable.b320);
		insertQuestion(db,R.string.question336, R.array.answers336,R.array.correct_answers336, R.string.category10, R.drawable.b1066);
		insertQuestion(db,R.string.question337, R.array.answers337,R.array.correct_answers337, R.string.category10, R.drawable.brak);
		insertQuestion(db,R.string.question338, R.array.answers338,R.array.correct_answers338, R.string.category10, R.drawable.b1196);
		insertQuestion(db,R.string.question339, R.array.answers339,R.array.correct_answers339, R.string.category10, R.drawable.brak);
		insertQuestion(db,R.string.question340, R.array.answers340,R.array.correct_answers340, R.string.category10, R.drawable.brak);
		insertQuestion(db,R.string.question341, R.array.answers341,R.array.correct_answers341, R.string.category10, R.drawable.brak);
		insertQuestion(db,R.string.question342, R.array.answers342,R.array.correct_answers342, R.string.category10, R.drawable.brak);
		insertQuestion(db,R.string.question343, R.array.answers343,R.array.correct_answers343, R.string.category10, R.drawable.brak);
		insertQuestion(db,R.string.question344, R.array.answers344,R.array.correct_answers344, R.string.category10, R.drawable.brak);
		insertQuestion(db,R.string.question345, R.array.answers345,R.array.correct_answers345, R.string.category10, R.drawable.brak);
		insertQuestion(db,R.string.question346, R.array.answers346,R.array.correct_answers346, R.string.category10, R.drawable.brak);
		insertQuestion(db,R.string.question347, R.array.answers347,R.array.correct_answers347, R.string.category10, R.drawable.brak);
		insertQuestion(db,R.string.question348, R.array.answers348,R.array.correct_answers348, R.string.category11, R.drawable.b322);
		insertQuestion(db,R.string.question349, R.array.answers349,R.array.correct_answers349, R.string.category11, R.drawable.b323);
		insertQuestion(db,R.string.question350, R.array.answers350,R.array.correct_answers350, R.string.category11, R.drawable.b324);
		insertQuestion(db,R.string.question351, R.array.answers351,R.array.correct_answers351, R.string.category11, R.drawable.b325);
		insertQuestion(db,R.string.question352, R.array.answers352,R.array.correct_answers352, R.string.category11, R.drawable.b327);
		insertQuestion(db,R.string.question353, R.array.answers353,R.array.correct_answers353, R.string.category11, R.drawable.b328);
		insertQuestion(db,R.string.question354, R.array.answers354,R.array.correct_answers354, R.string.category11, R.drawable.brak);
		insertQuestion(db,R.string.question355, R.array.answers355,R.array.correct_answers355, R.string.category11, R.drawable.brak);
		insertQuestion(db,R.string.question356, R.array.answers356,R.array.correct_answers356, R.string.category11, R.drawable.brak);
		insertQuestion(db,R.string.question357, R.array.answers357,R.array.correct_answers357, R.string.category11, R.drawable.brak);
		insertQuestion(db,R.string.question358, R.array.answers358,R.array.correct_answers358, R.string.category11, R.drawable.brak);
		insertQuestion(db,R.string.question359, R.array.answers359,R.array.correct_answers359, R.string.category11, R.drawable.b335);
		insertQuestion(db,R.string.question360, R.array.answers360,R.array.correct_answers360, R.string.category11, R.drawable.b336);
		insertQuestion(db,R.string.question361, R.array.answers361,R.array.correct_answers361, R.string.category11, R.drawable.brak);
		insertQuestion(db,R.string.question362, R.array.answers362,R.array.correct_answers362, R.string.category11, R.drawable.brak);
		insertQuestion(db,R.string.question363, R.array.answers363,R.array.correct_answers363, R.string.category11, R.drawable.brak);
		insertQuestion(db,R.string.question364, R.array.answers364,R.array.correct_answers364, R.string.category11, R.drawable.brak);
		insertQuestion(db,R.string.question365, R.array.answers365,R.array.correct_answers365, R.string.category11, R.drawable.b1067);
		insertQuestion(db,R.string.question366, R.array.answers366,R.array.correct_answers366, R.string.category11, R.drawable.brak);
		insertQuestion(db,R.string.question367, R.array.answers367,R.array.correct_answers367, R.string.category11, R.drawable.brak);
	}
}
