package pl.greenislanddev.prawojazdy.business.sql;

import pl.greenislanddev.prawojazdy.R;
import android.database.sqlite.SQLiteDatabase;

public class Category8DataCreator extends DbDataCreator {

	public void initData(final SQLiteDatabase db) {
		insertQuestion(db,R.string.question368, R.array.answers368,R.array.correct_answers368, R.string.category12, R.drawable.brak);
		insertQuestion(db,R.string.question369, R.array.answers369,R.array.correct_answers369, R.string.category12, R.drawable.brak);
		insertQuestion(db,R.string.question370, R.array.answers370,R.array.correct_answers370, R.string.category12, R.drawable.brak);
		insertQuestion(db,R.string.question371, R.array.answers371,R.array.correct_answers371, R.string.category12, R.drawable.brak);
		insertQuestion(db,R.string.question372, R.array.answers372,R.array.correct_answers372, R.string.category12, R.drawable.brak);
		insertQuestion(db,R.string.question373, R.array.answers373,R.array.correct_answers373, R.string.category12, R.drawable.brak);
		insertQuestion(db,R.string.question374, R.array.answers374,R.array.correct_answers374, R.string.category12, R.drawable.brak);
		insertQuestion(db,R.string.question375, R.array.answers375,R.array.correct_answers375, R.string.category12, R.drawable.brak);
		insertQuestion(db,R.string.question376, R.array.answers376,R.array.correct_answers376, R.string.category12, R.drawable.brak);
		insertQuestion(db,R.string.question377, R.array.answers377,R.array.correct_answers377, R.string.category12, R.drawable.brak);
		insertQuestion(db,R.string.question378, R.array.answers378,R.array.correct_answers378, R.string.category12, R.drawable.brak);
		insertQuestion(db,R.string.question379, R.array.answers379,R.array.correct_answers379, R.string.category12, R.drawable.brak);
		insertQuestion(db,R.string.question380, R.array.answers380,R.array.correct_answers380, R.string.category12, R.drawable.brak);
		insertQuestion(db,R.string.question381, R.array.answers381,R.array.correct_answers381, R.string.category12, R.drawable.brak);
		insertQuestion(db,R.string.question382, R.array.answers382,R.array.correct_answers382, R.string.category12, R.drawable.brak);
		insertQuestion(db,R.string.question383, R.array.answers383,R.array.correct_answers383, R.string.category12, R.drawable.brak);
		insertQuestion(db,R.string.question384, R.array.answers384,R.array.correct_answers384, R.string.category12, R.drawable.brak);
		insertQuestion(db,R.string.question385, R.array.answers385,R.array.correct_answers385, R.string.category12, R.drawable.brak);
		insertQuestion(db,R.string.question386, R.array.answers386,R.array.correct_answers386, R.string.category12, R.drawable.brak);
		insertQuestion(db,R.string.question387, R.array.answers387,R.array.correct_answers387, R.string.category12, R.drawable.brak);
		insertQuestion(db,R.string.question388, R.array.answers388,R.array.correct_answers388, R.string.category12, R.drawable.brak);
		insertQuestion(db,R.string.question389, R.array.answers389,R.array.correct_answers389, R.string.category12, R.drawable.brak);
		insertQuestion(db,R.string.question390, R.array.answers390,R.array.correct_answers390, R.string.category12, R.drawable.brak);
		insertQuestion(db,R.string.question391, R.array.answers391,R.array.correct_answers391, R.string.category13, R.drawable.b361);
		insertQuestion(db,R.string.question392, R.array.answers392,R.array.correct_answers392, R.string.category13, R.drawable.b367);
		insertQuestion(db,R.string.question393, R.array.answers393,R.array.correct_answers393, R.string.category13, R.drawable.b368);
		insertQuestion(db,R.string.question394, R.array.answers394,R.array.correct_answers394, R.string.category13, R.drawable.b370);
		insertQuestion(db,R.string.question395, R.array.answers395,R.array.correct_answers395, R.string.category13, R.drawable.b371);
		insertQuestion(db,R.string.question396, R.array.answers396,R.array.correct_answers396, R.string.category13, R.drawable.b372);
		insertQuestion(db,R.string.question397, R.array.answers397,R.array.correct_answers397, R.string.category13, R.drawable.b373);
		insertQuestion(db,R.string.question398, R.array.answers398,R.array.correct_answers398, R.string.category13, R.drawable.b374);
		insertQuestion(db,R.string.question399, R.array.answers399,R.array.correct_answers399, R.string.category13, R.drawable.b375);
		insertQuestion(db,R.string.question400, R.array.answers400,R.array.correct_answers400, R.string.category13, R.drawable.b376);
		insertQuestion(db,R.string.question401, R.array.answers401,R.array.correct_answers401, R.string.category13, R.drawable.brak);
		insertQuestion(db,R.string.question402, R.array.answers402,R.array.correct_answers402, R.string.category13, R.drawable.b378);
		insertQuestion(db,R.string.question403, R.array.answers403,R.array.correct_answers403, R.string.category13, R.drawable.b379);
		insertQuestion(db,R.string.question404, R.array.answers404,R.array.correct_answers404, R.string.category13, R.drawable.b380);
		insertQuestion(db,R.string.question405, R.array.answers405,R.array.correct_answers405, R.string.category13, R.drawable.b362);
		insertQuestion(db,R.string.question406, R.array.answers406,R.array.correct_answers406, R.string.category13, R.drawable.b369);
		insertQuestion(db,R.string.question407, R.array.answers407,R.array.correct_answers407, R.string.category13, R.drawable.b363n);
		insertQuestion(db,R.string.question408, R.array.answers408,R.array.correct_answers408, R.string.category13, R.drawable.b363n);
		insertQuestion(db,R.string.question409, R.array.answers409,R.array.correct_answers409, R.string.category13, R.drawable.b365n);
		insertQuestion(db,R.string.question410, R.array.answers410,R.array.correct_answers410, R.string.category13, R.drawable.b366n);
		insertQuestion(db,R.string.question411, R.array.answers411,R.array.correct_answers411, R.string.category14, R.drawable.b381);
		insertQuestion(db,R.string.question412, R.array.answers412,R.array.correct_answers412, R.string.category14, R.drawable.b382);
		insertQuestion(db,R.string.question413, R.array.answers413,R.array.correct_answers413, R.string.category14, R.drawable.b383);
		insertQuestion(db,R.string.question414, R.array.answers414,R.array.correct_answers414, R.string.category14, R.drawable.b384);
		insertQuestion(db,R.string.question415, R.array.answers415,R.array.correct_answers415, R.string.category14, R.drawable.b385);
		insertQuestion(db,R.string.question416, R.array.answers416,R.array.correct_answers416, R.string.category14, R.drawable.b386);
		insertQuestion(db,R.string.question417, R.array.answers417,R.array.correct_answers417, R.string.category14, R.drawable.b387);
		insertQuestion(db,R.string.question418, R.array.answers418,R.array.correct_answers418, R.string.category14, R.drawable.b388);
		insertQuestion(db,R.string.question419, R.array.answers419,R.array.correct_answers419, R.string.category14, R.drawable.b389);
		insertQuestion(db,R.string.question420, R.array.answers420,R.array.correct_answers420, R.string.category14, R.drawable.b390);
		insertQuestion(db,R.string.question421, R.array.answers421,R.array.correct_answers421, R.string.category14, R.drawable.b391);
		insertQuestion(db,R.string.question422, R.array.answers422,R.array.correct_answers422, R.string.category14, R.drawable.b392);
		insertQuestion(db,R.string.question423, R.array.answers423,R.array.correct_answers423, R.string.category14, R.drawable.b393);
		insertQuestion(db,R.string.question424, R.array.answers424,R.array.correct_answers424, R.string.category14, R.drawable.b394);
		insertQuestion(db,R.string.question425, R.array.answers425,R.array.correct_answers425, R.string.category14, R.drawable.b395);
		insertQuestion(db,R.string.question426, R.array.answers426,R.array.correct_answers426, R.string.category14, R.drawable.b396);
		insertQuestion(db,R.string.question427, R.array.answers427,R.array.correct_answers427, R.string.category14, R.drawable.b397);
		insertQuestion(db,R.string.question428, R.array.answers428,R.array.correct_answers428, R.string.category14, R.drawable.b398);
		insertQuestion(db,R.string.question429, R.array.answers429,R.array.correct_answers429, R.string.category14, R.drawable.b399);
		insertQuestion(db,R.string.question430, R.array.answers430,R.array.correct_answers430, R.string.category14, R.drawable.b400);
		insertQuestion(db,R.string.question431, R.array.answers431,R.array.correct_answers431, R.string.category14, R.drawable.b524n);
		insertQuestion(db,R.string.question432, R.array.answers432,R.array.correct_answers432, R.string.category14, R.drawable.b525n);
		insertQuestion(db,R.string.question433, R.array.answers433,R.array.correct_answers433, R.string.category15, R.drawable.brak);
		insertQuestion(db,R.string.question434, R.array.answers434,R.array.correct_answers434, R.string.category15, R.drawable.brak);
		insertQuestion(db,R.string.question435, R.array.answers435,R.array.correct_answers435, R.string.category15, R.drawable.brak);
		insertQuestion(db,R.string.question436, R.array.answers436,R.array.correct_answers436, R.string.category15, R.drawable.brak);
		insertQuestion(db,R.string.question437, R.array.answers437,R.array.correct_answers437, R.string.category15, R.drawable.brak);
		insertQuestion(db,R.string.question438, R.array.answers438,R.array.correct_answers438, R.string.category15, R.drawable.b406);
		insertQuestion(db,R.string.question439, R.array.answers439,R.array.correct_answers439, R.string.category15, R.drawable.b407);
		insertQuestion(db,R.string.question440, R.array.answers440,R.array.correct_answers440, R.string.category15, R.drawable.brak);
		insertQuestion(db,R.string.question441, R.array.answers441,R.array.correct_answers441, R.string.category15, R.drawable.b410);
		insertQuestion(db,R.string.question442, R.array.answers442,R.array.correct_answers442, R.string.category15, R.drawable.brak);
		insertQuestion(db,R.string.question443, R.array.answers443,R.array.correct_answers443, R.string.category15, R.drawable.brak);
		insertQuestion(db,R.string.question444, R.array.answers444,R.array.correct_answers444, R.string.category15, R.drawable.brak);
		insertQuestion(db,R.string.question445, R.array.answers445,R.array.correct_answers445, R.string.category15, R.drawable.brak);
		insertQuestion(db,R.string.question446, R.array.answers446,R.array.correct_answers446, R.string.category15, R.drawable.brak);
		insertQuestion(db,R.string.question447, R.array.answers447,R.array.correct_answers447, R.string.category15, R.drawable.brak);
		insertQuestion(db,R.string.question448, R.array.answers448,R.array.correct_answers448, R.string.category15, R.drawable.brak);
		insertQuestion(db,R.string.question449, R.array.answers449,R.array.correct_answers449, R.string.category15, R.drawable.brak);
		insertQuestion(db,R.string.question450, R.array.answers450,R.array.correct_answers450, R.string.category15, R.drawable.brak);
		insertQuestion(db,R.string.question451, R.array.answers451,R.array.correct_answers451, R.string.category15, R.drawable.b420);
		insertQuestion(db,R.string.question452, R.array.answers452,R.array.correct_answers452, R.string.category15, R.drawable.b409n);
		insertQuestion(db,R.string.question453, R.array.answers453,R.array.correct_answers453, R.string.category15, R.drawable.brak);
	}

}
